# Site wide configuration

title: containers workshop
description: "Hands-on with container technology"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //containers-workshop.neependra.net
#url: //127.0.0.1:4000

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Neependra Khare
  web: http://neependra.net
  email: neependra.khare@gmail.com
  twitter: neependra
  bio: "Container Evangelist, Trainer, Author"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +NeependraKhare
    ad-client: 
    ad-slot:
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
